/*Authors: Mateusz Simkiewicz, Michał Wieczorek, Szymon Kulej.*/
DROP DATABASE IF EXISTS `WCALENIESEX`;
CREATE DATABASE `WCALENIESEX`;
USE `WCALENIESEX`;
/*Trzeba jeszcze zmienić nazwy tabeli ale ja(Michał) o zrobie*/

CREATE TABLE `ACCOUNT`
(
    `ID_ACCOUNT` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `LOGIN` VARCHAR(30),
    `PASSWORD` VARCHAR(30),
    `PHONE` INT(9),
    `EMAIL` VARCHAR(30),
    `NICKNAME` VARCHAR(30),
    `TAG` INT(4),
    `ABOUTME` VARCHAR(150),
    `STATUS` VARCHAR(30),
    `ACTIVITY` INT(1), /*1-Online, 2-Do not distrub, 3-Idle, 4-Offline*/
    `PFP` BLOB,
    `BANER` BLOB
);

CREATE TABLE `FRIENDSHIP`
(
    `ID_FRIENDSHIP1` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `ID_ACCOUNT1` INT(11), /*FK*/
    `ID_ACCOUNT2` INT(11), /*FK*/
    `STATUS1` INT(1) /*reqested 0 accepted 1 rejected 2 unfriended 3 blocked 4*/
);

CREATE TABLE `CHAT`
(
    `ID_CHAT1` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `MESSAGEDATE1` DATETIME,
    `CONTENT` VARCHAR(512)
);

CREATE TABLE `CHAT-ACCOUNT`
(
    `ID_CHAT-ACCOUNT` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `ID_CHAT` INT(11), /*FK*/
    `ID_ACCOUNT` INT(11) /*FK*/
);

CREATE TABLE `PERMISSION`
(
    `ID_PERMISSION` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `PERMISSIONNAME` VARCHAR(255)
    `PERMISSIONVALUE` INT(1)
    `PERMISSIONDESC` VARCHAR(255)
);

CREATE TABLE `SERVER`
(
    `ID_SERVER` INT(11) PRIMARY KEY AUTO_INCREMENT,
);

CREATE TABLE `ROLES`
(
    `ID_ROLES` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `ROLENAME` VARCHAR(32),
    `ID_PERMISSION` INT(11),
    `COLOR` VARCHAR(7),
    `WEIGHT` INT(3),
    `ID_SERVER` INT(11) /*FK*/
);

CREATE TABLE `INVITE`
(
    `ID_INVITE` VARCHAR(11) PRIMARY KEY,
    `ID_SERVER` INT(11), /*FK*/
    `EXPIRE_DATE` DATETIME,
    `CREATE_DATE` DATETIME,
    `ID_USER` INT(11) /*FK*/
);

/*DELIMITER &&
CREATE PROCEDURE `INVITEREFRESH`
BEGIN

end &&
delimiter ;*/

CREATE TABLE `CATEGORY`
(
    `ID_CATEGORY` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `ID_SERVER` INT(11), /*FK*/
);

CREATE TABLE `CHANNEL`
(
    `ID_CHANNEL` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `ID_CATEGORRY` INT(11), /*FK*/
);

CREATE TABLE `SERVER-ACCOUNT-ROLES`
(
    `ID_SERVER-ACCOUNT` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `ID_SERVER` INT(11), /*FK*/
    `ID_ACCOUNT` INT(11), /*FK*/
    `ID_ROLES` INT(11) /*FK*/
);